name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]  # or whichever branch you want to trigger from
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write  # Required for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Install dependencies
        run: python -m pip install sphinx sphinx-autodoc-typehints
      - name: Build Sphinx HTML
        run: cd docs-sphinx && make html
      - name: Construct main page
        run: |
          cd docs-sphinx/build
          rm -rf doctrees
          mv html api
          pandoc ../../mainpage.md -s -o index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-sphinx/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
